version: '3'
services:
  errandlr-api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WAIT_HOSTS=mongo:27017
      - WAIT_SLEEP_INTERVAL=5
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    command: sh -c "/wait && yarn dev"
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
#Refs
# https://github.com/docker/compose/issues/2033
# https://stackoverflow.com/questions/26522789/how-to-run-sh-on-windows-command-prompt
