version: '3'
services:
  pickfu-api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WAIT_HOSTS=mongo:27017
      - WAIT_SLEEP_INTERVAL=5
    env_file:
      - .env
    depends_on:
      - mongo
    command: sh -c "/wait && yarn build && yarn start"
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
